In [12]:
from submission_to_surprise import *
from surprise import *
from surprise.model_selection import cross_validate
import pandas as pd

In [13]:
data_folder = 'csv/'

In [3]:
# submission_to_surprise(data_folder + 'data_train.csv')

In [14]:
df = pd.read_csv(data_folder + 'surprise_train.csv')
#df = df[['User', 'Item', 'Prediction']]
df

          User  Item  Rating
0           44     1       4
1           61     1       3
2           67     1       4
3           72     1       3
4           86     1       5
5           90     1       4
6          108     1       3
7          114     1       3
8          120     1       2
9          135     1       5
10         152     1       4
11         165     1       3
12         182     1       3
13         310     1       3
14         318     1       1
15         333     1       3
16         355     1       2
17         390     1       4
18         401     1       4
19         410     1       2
20         418     1       3
21         457     1       2
22         470     1       4
23         497     1       3
24         516     1       3
25         566     1       3
26         595     1       2
27         670     1       3
28         673     1       4
29         708     1       1
...        ...   ...     ...
1176922   9846  1000       3
1176923   9855  1000       4
1176924   9867  1000       3
1176925   9874  1000       5
1176926   9875  1000       3
1176927   9884  1000       2
1176928   9890  1000       5
1176929   9904  1000       5
1176930   9909  1000       4
1176931   9913  1000       2
1176932   9922  1000       3
1176933   9925  1000       3
1176934   9929  1000       4
1176935   9936  1000       2
1176936   9944  1000       4
1176937   9945  1000       5
1176938   9949  1000       4
1176939   9957  1000       3
1176940   9958  1000       4
1176941   9960  1000       3
1176942   9961  1000       4
1176943   9964  1000       3
1176944   9968  1000       5
1176945   9970  1000       5
1176946   9976  1000       5
1176947   9990  1000       4
1176948   9992  1000       5
1176949   9994  1000       3
1176950   9997  1000       4
1176951  10000  1000       3

[1176952 rows x 3 columns]

In [16]:
#reader = Reader(line_format='item user rating', sep=',', skip_lines=1)
#data = Dataset.load_from_file(data_folder + 'surprise_train.csv', reader=reader)
reader = Reader(rating_scale=(1, 5))
data = Dataset.load_from_df(df[['User', 'Item', 'Rating']], reader)

In [17]:
algo = SVD(n_epochs=20,n_factors=100, biased=True, verbose=True)
cross_validate(algo, data, measures=['RMSE', 'MAE'], cv=5, verbose=True, n_jobs=-1, pre_dispatch=2)

Evaluating RMSE, MAE of algorithm SVD on 5 split(s).

                  Fold 1  Fold 2  Fold 3  Fold 4  Fold 5  Mean    Std
RMSE (testset)    1.0291  1.0259  1.0279  1.0245  1.0301  1.0275  0.0020
MAE (testset)     0.8221  0.8186  0.8199  0.8177  0.8216  0.8200  0.0017
Fit time          59.66   60.09   57.85   56.55   55.18   57.87   1.85
Test time         1.84    2.00    1.86    1.90    1.88    1.90    0.06

{'test_rmse': array([1.02913679, 1.02592   , 1.02790771, 1.02450963, 1.03009216]),
 'test_mae': array([0.82214715, 0.81856952, 0.81991071, 0.81767032, 0.82156584]),
 'fit_time': (59.66326951980591,
  60.089571952819824,
  57.84753108024597,
  56.549224615097046,
  55.17809176445007),
 'test_time': (1.8353018760681152,
  2.0044217109680176,
  1.8643207550048828,
  1.9013464450836182,
  1.876343011856079)}

In [18]:
trainset = data.build_full_trainset()
algo = SVD(n_epochs=20,n_factors=100, biased=True, verbose=True)
algo.fit(trainset)

Processing epoch 0
Processing epoch 1
Processing epoch 2
Processing epoch 3
Processing epoch 4
Processing epoch 5
Processing epoch 6
Processing epoch 7
Processing epoch 8
Processing epoch 9
Processing epoch 10
Processing epoch 11
Processing epoch 12
Processing epoch 13
Processing epoch 14
Processing epoch 15
Processing epoch 16
Processing epoch 17
Processing epoch 18
Processing epoch 19

In [19]:
ids, _ = get_ids_values(data_folder + 'sampleSubmission.csv')
item, user = replace_ids_submission(ids)
prediction = np.zeros(len(item))
for i in range(len(prediction)):
    prediction[i] = algo.predict(user[i], item[i], None, True, False).est

In [9]:
create_csv_submission(ids, prediction, 'submission.csv')

In [23]:
int(np.round(3.4999))

3